#!/usr/bin/env python3
"""
Resolve physical hash bundle filenames using BundleList.txt.

Expected BundleList row format:
    logical_bundle_name,hash,size,flag

Author:
    Kenshin | Darkside TH | Odin Valhalla | ROXLab Researcher

Notes:
    This script performs mapping only.
    It does not modify, patch, execute, bypass, or manipulate game files.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path
from typing import Dict, Tuple


def normalize_hash(value: str) -> str:
    """Normalize a bundle hash or physical filename into lowercase hash text."""
    value = (value or "").strip().lower()

    if value.endswith(".bundle"):
        value = value[:-7]

    return value


def read_bundle_list(bundle_list_path: Path) -> Dict[str, Tuple[str, int, str, str]]:
    """
    Read BundleList.txt and return mapping:
        hash -> (logical_name, line_number, declared_size, flag)
    """
    mapping: Dict[str, Tuple[str, int, str, str]] = {}

    with bundle_list_path.open("r", encoding="utf-8", errors="replace") as f:
        for line_number, raw_line in enumerate(f, 1):
            line = raw_line.strip()

            if not line:
                continue

            parts = [part.strip() for part in line.split(",")]

            if len(parts) < 2:
                continue

            logical_name = parts[0]
            hash_value = normalize_hash(parts[1])
            declared_size = parts[2] if len(parts) > 2 else ""
            flag = parts[3] if len(parts) > 3 else ""

            if not logical_name or not hash_value:
                continue

            mapping[hash_value] = (logical_name, line_number, declared_size, flag)

    return mapping


def read_inventory_csv(inventory_csv_path: Path) -> list[dict[str, str]]:
    """Read exported bundle inventory CSV from PowerShell."""
    with inventory_csv_path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def resolve_bundle_names(
    inventory_csv_path: Path,
    bundle_list_path: Path,
    output_csv_path: Path,
) -> tuple[int, int]:
    """Resolve physical hash filenames to logical bundle names."""
    mapping = read_bundle_list(bundle_list_path)
    inventory_rows = read_inventory_csv(inventory_csv_path)

    fieldnames = [
        "Resolved",
        "PhysicalFilename",
        "OriginalName",
        "Hash",
        "PhysicalSizeBytes",
        "BundleListDeclaredSize",
        "PhysicalLastWriteTime",
        "BundleListLine",
        "BundleListFlag",
        "PhysicalFullPath",
    ]

    resolved_count = 0
    unresolved_count = 0

    with output_csv_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()

        for row in inventory_rows:
            filename = row.get("Name", "").strip()
            hash_value = normalize_hash(filename)

            logical_name, line_number, declared_size, flag = mapping.get(
                hash_value,
                ("UNRESOLVED", "", "", ""),
            )

            resolved = logical_name != "UNRESOLVED"

            if resolved:
                resolved_count += 1
            else:
                unresolved_count += 1

            writer.writerow(
                {
                    "Resolved": str(resolved).upper(),
                    "PhysicalFilename": filename,
                    "OriginalName": logical_name,
                    "Hash": hash_value,
                    "PhysicalSizeBytes": row.get("Length", ""),
                    "BundleListDeclaredSize": declared_size,
                    "PhysicalLastWriteTime": row.get("LastWriteTime", ""),
                    "BundleListLine": line_number,
                    "BundleListFlag": flag,
                    "PhysicalFullPath": row.get("FullName", ""),
                }
            )

    return resolved_count, unresolved_count


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Resolve hashed Unity AssetBundle filenames using BundleList.txt."
    )

    parser.add_argument(
        "inventory_csv",
        type=Path,
        help="CSV generated by export_bundle_inventory.ps1.",
    )

    parser.add_argument(
        "bundle_list",
        type=Path,
        help="BundleList.txt containing logical_bundle_name,hash,size,flag rows.",
    )

    parser.add_argument(
        "output_csv",
        type=Path,
        help="Output CSV path for resolved mapping.",
    )

    return parser


def main() -> int:
    parser = build_arg_parser()
    args = parser.parse_args()

    inventory_csv_path: Path = args.inventory_csv
    bundle_list_path: Path = args.bundle_list
    output_csv_path: Path = args.output_csv

    if not inventory_csv_path.exists():
        print(f"Inventory CSV not found: {inventory_csv_path}", file=sys.stderr)
        return 1

    if not bundle_list_path.exists():
        print(f"BundleList.txt not found: {bundle_list_path}", file=sys.stderr)
        return 1

    output_csv_path.parent.mkdir(parents=True, exist_ok=True)

    resolved_count, unresolved_count = resolve_bundle_names(
        inventory_csv_path=inventory_csv_path,
        bundle_list_path=bundle_list_path,
        output_csv_path=output_csv_path,
    )

    print("ROX Bundle Hash Resolver")
    print("Author: Kenshin | Darkside TH | Odin Valhalla | ROXLab Researcher")
    print("")
    print(f"Resolved: {resolved_count}")
    print(f"Unresolved: {unresolved_count}")
    print(f"Output: {output_csv_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
